global:
  scrape_interval:     1m 
  evaluation_interval: 1m
  external_labels:
      monitor: 'Monitoring'

#rule_files:
#  - /etc/prometheus/alert.rules
#alerting:
#  alertmanagers:
#    - scheme: http
#      static_configs:
#      - targets:
#        - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus server'
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: 'node exporter'
    static_configs:
      - targets:
        - node-exporter:9100
  - job_name: "snmp exporter"
    metrics_path: /snmp
    params:
      module: [snmp]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116
    file_sd_configs:
      - files:
          - '/etc/prometheus/file_sd_config/snmp_exporter.yml'
